### ISSUE TITLE
Getting - Error: socket hang up when execute  "node registerUser.js"

### ISSUE THREAD

**Issue by dewminic** [IBM/fabcar-blockchain-sample#59]
Getting below error when execute "node registerUser.js" . I tried with node version 12.20.0 ,  14.15.4 but issue is same and not sure exact reason for the issue. Could you please assist me to troubleshoot the issue.

Failed to register user user1: Error: Calling register endpoint failed with error [Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}]

**Comment by dewminic** [comment]
I could fix the issue by changing the node version to 10.23.1, and restart the vs code.
